import type { AdSlot, Listing, Purchase } from "./types";

export const LISTINGS: Listing[] = [
  {
    id: "maya-laptop-lid",
    title: "Ten spots on my MacBook lid",
    category: "laptop",
    itemModel: "MacBook Pro, 14-inch lid",
    status: "live",
    contexts: ["coffee_shops", "video_calls", "campus"],
    city: "Austin",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    durationMonths: 12,
    endsAt: "2027-03-01",
    proofPhotoUrl: null,
    spots: [
      { id: "maya-1", label: "Top left banner", size: "large", dimensionsCm: "9.5 × 5.5 cm", price: 58, takenBy: null },
      { id: "maya-2", label: "Marquee — above the logo", size: "large", dimensionsCm: "9.5 × 5.5 cm", price: 75, takenBy: null },
      { id: "maya-3", label: "Top right banner", size: "large", dimensionsCm: "9.5 × 5.5 cm", price: 58, takenBy: null },
      { id: "maya-4", label: "Middle left", size: "small", dimensionsCm: "4.5 × 4.5 cm", price: 16, takenBy: null },
      { id: "maya-5", label: "Inner left — beside the logo", size: "small", dimensionsCm: "4.5 × 4.5 cm", price: 19, takenBy: null },
      { id: "maya-6", label: "Inner right — beside the logo", size: "small", dimensionsCm: "4.5 × 4.5 cm", price: 19, takenBy: null },
      { id: "maya-7", label: "Middle right", size: "small", dimensionsCm: "4.5 × 4.5 cm", price: 16, takenBy: null },
      { id: "maya-8", label: "Bottom left strip", size: "medium", dimensionsCm: "9.5 × 4 cm", price: 28, takenBy: null },
      { id: "maya-9", label: "Bottom centre — under the logo", size: "medium", dimensionsCm: "9.5 × 4 cm", price: 34, takenBy: null },
      { id: "maya-10", label: "Bottom right strip", size: "medium", dimensionsCm: "9.5 × 4 cm", price: 28, takenBy: null },
    ],
    seller: {
      id: "maya",
      name: "Maya R.",
      handle: "@MayaBuildsThings",
      avatarInitial: "M",
      memberSince: "2025",
      listingsCount: 6,
      followers: 940,
      verified: true,
      role: "Indie hacker",
    },
    createdAt: "2026-08-20",
  },
  {
    id: "devon-bottle",
    title: "Spots on my 32oz bottle",
    category: "water_bottle",
    itemModel: "Hydro Flask, 32oz",
    status: "live",
    contexts: ["gym", "commute"],
    city: "Denver",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    durationMonths: 6,
    endsAt: "2027-01-15",
    proofPhotoUrl: null,
    spots: [
      { id: "devon-1", label: "Front label", size: "large", dimensionsCm: "8 × 6 cm", price: 30, takenBy: null },
      { id: "devon-2", label: "Side wrap, left", size: "medium", dimensionsCm: "6 × 4 cm", price: 20, takenBy: null },
      { id: "devon-3", label: "Side wrap, right", size: "medium", dimensionsCm: "6 × 4 cm", price: 20, takenBy: "Cursorly" },
      { id: "devon-4", label: "Cap band", size: "small", dimensionsCm: "3 × 2 cm", price: 10, takenBy: null },
    ],
    seller: {
      id: "devon",
      name: "Devon K.",
      handle: "@DevonRuns",
      avatarInitial: "D",
      memberSince: "2025",
      listingsCount: 2,
      followers: 210,
      verified: false,
      role: "Fitness creator",
    },
    createdAt: "2026-08-22",
  },
  {
    id: "priya-backpack",
    title: "Front pocket, fully claimed",
    category: "backpack",
    itemModel: "Cotopaxi backpack, front pocket",
    status: "live",
    contexts: ["campus", "commute"],
    city: "Chicago",
    state: "IL",
    lat: 41.8781,
    lng: -87.6298,
    durationMonths: 4,
    endsAt: "2026-12-10",
    proofPhotoUrl: null,
    spots: [
      { id: "priya-1", label: "Front pocket, centre", size: "medium", dimensionsCm: "7 × 7 cm", price: 24, takenBy: "Fieldnote" },
    ],
    seller: {
      id: "priya",
      name: "Priya S.",
      handle: "@PriyaOnCampus",
      avatarInitial: "P",
      memberSince: "2024",
      listingsCount: 4,
      followers: 560,
      verified: false,
      role: "Student · CS major",
    },
    createdAt: "2026-08-18",
  },
  {
    id: "sam-phone-case",
    title: "One spot, back panel",
    category: "phone_case",
    itemModel: "iPhone 15 case, back panel",
    status: "live",
    contexts: ["coffee_shops", "campus"],
    city: "Brooklyn",
    state: "NY",
    lat: 40.6782,
    lng: -73.9442,
    durationMonths: 6,
    endsAt: "2027-02-27",
    proofPhotoUrl: null,
    spots: [
      { id: "sam-1", label: "Back panel", size: "small", dimensionsCm: "5 × 5 cm", price: 18, takenBy: "Cursorly" },
    ],
    seller: {
      id: "sam",
      name: "Sam T.",
      handle: "@SamShoots",
      avatarInitial: "S",
      memberSince: "2026",
      listingsCount: 1,
      followers: 88,
      verified: false,
      role: "Photographer",
    },
    createdAt: "2026-08-27",
  },
  {
    id: "owen-bike",
    title: "Three spots on my bike frame",
    category: "bike",
    itemModel: "Trek FX 3, aluminum frame",
    status: "live",
    contexts: ["commute", "gym"],
    city: "Portland",
    state: "OR",
    lat: 45.5152,
    lng: -122.6784,
    durationMonths: 8,
    endsAt: "2027-04-30",
    proofPhotoUrl: null,
    spots: [
      { id: "owen-1", label: "Top tube, left", size: "medium", dimensionsCm: "8 × 4 cm", price: 20, takenBy: null },
      { id: "owen-2", label: "Top tube, right", size: "medium", dimensionsCm: "8 × 4 cm", price: 20, takenBy: null },
      { id: "owen-3", label: "Down tube", size: "large", dimensionsCm: "12 × 6 cm", price: 40, takenBy: "Northwind" },
    ],
    seller: {
      id: "owen",
      name: "Owen M.",
      handle: "@OwenRidesPDX",
      avatarInitial: "O",
      memberSince: "2025",
      listingsCount: 3,
      followers: 1200,
      verified: true,
      role: "Cycling creator",
    },
    createdAt: "2026-08-15",
  },
  {
    id: "lena-car",
    title: "Three spots on my rear bumper",
    category: "car",
    itemModel: "Honda Civic, rear bumper",
    status: "live",
    contexts: ["commute"],
    city: "Raleigh",
    state: "NC",
    lat: 35.7796,
    lng: -78.6382,
    durationMonths: 12,
    endsAt: "2027-08-10",
    proofPhotoUrl: null,
    spots: [
      { id: "lena-1", label: "Left bumper", size: "large", dimensionsCm: "12 × 5 cm", price: 35, takenBy: null },
      { id: "lena-2", label: "Centre bumper", size: "large", dimensionsCm: "14 × 5 cm", price: 40, takenBy: "Northwind" },
      { id: "lena-3", label: "Right bumper", size: "large", dimensionsCm: "12 × 5 cm", price: 35, takenBy: null },
    ],
    seller: {
      id: "lena",
      name: "Lena T.",
      handle: "@LenaDrives",
      avatarInitial: "L",
      memberSince: "2024",
      listingsCount: 5,
      followers: 340,
      verified: false,
      role: "Sales rep",
    },
    createdAt: "2026-08-10",
  },
  {
    id: "ravi-laptop-back",
    title: "One spot, back panel",
    category: "laptop",
    itemModel: "MacBook Air, 13-inch lid",
    status: "live",
    contexts: ["campus"],
    city: "Ann Arbor",
    state: "MI",
    lat: 42.2808,
    lng: -83.743,
    durationMonths: 6,
    endsAt: "2027-02-19",
    proofPhotoUrl: null,
    spots: [
      { id: "ravi-1", label: "Back panel, centre", size: "large", dimensionsCm: "9.5 × 5.5 cm", price: 38, takenBy: null },
    ],
    seller: {
      id: "ravi",
      name: "Ravi P.",
      handle: "@RaviTeaches",
      avatarInitial: "R",
      memberSince: "2025",
      listingsCount: 2,
      followers: 175,
      verified: false,
      role: "Grad student",
    },
    createdAt: "2026-08-19",
  },
  {
    id: "jo-backpack-side",
    title: "One spot, side pocket",
    category: "backpack",
    itemModel: "Osprey daypack, side pocket",
    status: "live",
    contexts: ["gym", "campus"],
    city: "Seattle",
    state: "WA",
    lat: 47.6062,
    lng: -122.3321,
    durationMonths: 4,
    endsAt: "2026-12-29",
    proofPhotoUrl: null,
    spots: [
      { id: "jo-1", label: "Side pocket", size: "small", dimensionsCm: "5 × 5 cm", price: 16, takenBy: null },
    ],
    seller: {
      id: "jo",
      name: "Jo L.",
      handle: "@JoHikes",
      avatarInitial: "J",
      memberSince: "2026",
      listingsCount: 1,
      followers: 430,
      verified: false,
      role: "Outdoor creator",
    },
    createdAt: "2026-08-29",
  },
];

export function getListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}

export function getSpot(listing: Listing, spotId: string) {
  return listing.spots.find((s) => s.id === spotId);
}

export const ADMIN_REVIEW_QUEUE: {
  id: string;
  item: string;
  seller: string;
  category: string;
  price: number;
  submittedHoursAgo: number;
}[] = [
  { id: "q1", item: "Ten spots on my MacBook lid", seller: "Maya R.", category: "Laptop", price: 58, submittedHoursAgo: 2 },
  { id: "q2", item: "Spots on my 32oz bottle", seller: "Devon K.", category: "Water bottle", price: 30, submittedHoursAgo: 5 },
  { id: "q3", item: "Front pocket, fully claimed", seller: "Priya S.", category: "Backpack", price: 24, submittedHoursAgo: 9 },
  { id: "q4", item: "Three spots on my rear bumper", seller: "Lena T.", category: "Car", price: 40, submittedHoursAgo: 24 },
  { id: "q5", item: "Three spots on my bike frame", seller: "Owen M.", category: "Bike", price: 40, submittedHoursAgo: 26 },
];

export const AD_SLOTS: AdSlot[] = [
  {
    id: "homepage-banner",
    kind: "homepage_banner",
    title: "Homepage banner",
    description: "Full-width strip above the marketplace grid. Highest visibility on the site.",
    price: 500,
    available: true,
  },
  {
    id: "category-sidebar",
    kind: "category_sidebar",
    title: "Category sidebar",
    description: "Rail alongside browse results, shown while people filter by category.",
    price: 150,
    available: true,
  },
  {
    id: "sponsored-listing",
    kind: "sponsored_listing",
    title: "Sponsored listing slot",
    description: "Sits inside the marketplace grid, styled like a listing but clearly labeled.",
    price: 75,
    available: true,
  },
];

export const JUST_SOLD: { brand: string; listingId: string; spotLabel: string; price: number; hoursAgo: number }[] = [
  { brand: "Northwind", listingId: "owen-bike", spotLabel: "down tube", price: 40, hoursAgo: 2 },
  { brand: "Fieldnote", listingId: "priya-backpack", spotLabel: "front pocket", price: 24, hoursAgo: 6 },
  { brand: "Cursorly", listingId: "devon-bottle", spotLabel: "side wrap", price: 20, hoursAgo: 9 },
  { brand: "Northwind", listingId: "lena-car", spotLabel: "centre bumper", price: 40, hoursAgo: 14 },
];

export const SELLER_PURCHASES: Purchase[] = [
  {
    id: "req-1",
    listing: getListing("maya-laptop-lid")!,
    spotId: "maya-2",
    brandName: "Northwind",
    price: 75,
    status: "awaiting_approval",
    purchasedAt: "2026-09-03T10:00:00Z",
  },
  {
    id: "req-2",
    listing: getListing("maya-laptop-lid")!,
    spotId: "maya-1",
    brandName: "Fieldnote",
    price: 58,
    status: "awaiting_approval",
    purchasedAt: "2026-09-02T14:00:00Z",
  },
];

export const BRAND_PURCHASES: Purchase[] = [
  {
    id: "b-1",
    listing: getListing("maya-laptop-lid")!,
    spotId: "maya-2",
    brandName: "Northwind",
    price: 75,
    status: "awaiting_approval",
    purchasedAt: "2026-09-03T10:00:00Z",
  },
  {
    id: "b-2",
    listing: getListing("owen-bike")!,
    spotId: "owen-3",
    brandName: "Northwind",
    price: 40,
    status: "live",
    purchasedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "b-3",
    listing: getListing("lena-car")!,
    spotId: "lena-2",
    brandName: "Northwind",
    price: 40,
    status: "live",
    purchasedAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "b-4",
    listing: getListing("devon-bottle")!,
    spotId: "devon-3",
    brandName: "Northwind",
    price: 20,
    status: "expired",
    purchasedAt: "2026-06-01T10:00:00Z",
  },
];
