import type { AdSlot, Listing, Purchase } from "./types";

export const LISTINGS: Listing[] = [
  {
    id: "maya-laptop-lid",
    title: '14" MacBook lid, top panel',
    category: "laptop",
    placement: "Top-right corner",
    stickerSize: "3in x 3in decal",
    price: 45,
    durationDays: 30,
    status: "live",
    contexts: ["coffee_shops", "video_calls", "campus"],
    city: "Austin",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    seller: {
      id: "maya",
      name: "Maya R.",
      avatarInitial: "M",
      memberSince: "2025",
      listingsCount: 6,
      rating: 4.9,
    },
    createdAt: "2026-08-20",
  },
  {
    id: "devon-bottle",
    title: "32oz bottle, full wrap",
    category: "water_bottle",
    placement: "Full wrap",
    stickerSize: "8in x 3in decal",
    price: 28,
    durationDays: 30,
    status: "live",
    contexts: ["gym", "commute"],
    city: "Denver",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    seller: {
      id: "devon",
      name: "Devon K.",
      avatarInitial: "D",
      memberSince: "2025",
      listingsCount: 2,
      rating: 4.7,
    },
    createdAt: "2026-08-22",
  },
  {
    id: "priya-backpack",
    title: "Backpack front pocket",
    category: "backpack",
    placement: "Front pocket",
    stickerSize: "4in x 4in decal",
    price: 22,
    durationDays: 21,
    status: "sold",
    contexts: ["campus", "commute"],
    city: "Chicago",
    state: "IL",
    lat: 41.8781,
    lng: -87.6298,
    seller: {
      id: "priya",
      name: "Priya S.",
      avatarInitial: "P",
      memberSince: "2024",
      listingsCount: 4,
      rating: 5.0,
    },
    createdAt: "2026-08-18",
  },
  {
    id: "sam-phone-case",
    title: "Phone case, back panel",
    category: "phone_case",
    placement: "Back panel",
    stickerSize: "2in x 2in decal",
    price: 18,
    durationDays: 30,
    status: "live",
    contexts: ["coffee_shops", "campus"],
    city: "Brooklyn",
    state: "NY",
    lat: 40.6782,
    lng: -73.9442,
    seller: {
      id: "sam",
      name: "Sam T.",
      avatarInitial: "S",
      memberSince: "2026",
      listingsCount: 1,
      rating: 4.8,
    },
    createdAt: "2026-08-27",
  },
  {
    id: "owen-bike",
    title: "Bike frame, top tube",
    category: "bike",
    placement: "Top tube",
    stickerSize: "6in x 2in decal",
    price: 34,
    durationDays: 45,
    status: "live",
    contexts: ["commute", "gym"],
    city: "Portland",
    state: "OR",
    lat: 45.5152,
    lng: -122.6784,
    seller: {
      id: "owen",
      name: "Owen M.",
      avatarInitial: "O",
      memberSince: "2025",
      listingsCount: 3,
      rating: 4.9,
    },
    createdAt: "2026-08-15",
  },
  {
    id: "lena-car",
    title: "Rear bumper, driver side",
    category: "car",
    placement: "Driver-side bumper",
    stickerSize: "10in x 4in decal",
    price: 60,
    durationDays: 60,
    status: "live",
    contexts: ["commute"],
    city: "Raleigh",
    state: "NC",
    lat: 35.7796,
    lng: -78.6382,
    seller: {
      id: "lena",
      name: "Lena T.",
      avatarInitial: "L",
      memberSince: "2024",
      listingsCount: 5,
      rating: 4.6,
    },
    createdAt: "2026-08-10",
  },
  {
    id: "ravi-laptop-back",
    title: '13" laptop, back panel',
    category: "laptop",
    placement: "Back panel",
    stickerSize: "3in x 3in decal",
    price: 38,
    durationDays: 30,
    status: "live",
    contexts: ["campus"],
    city: "Ann Arbor",
    state: "MI",
    lat: 42.2808,
    lng: -83.743,
    seller: {
      id: "ravi",
      name: "Ravi P.",
      avatarInitial: "R",
      memberSince: "2025",
      listingsCount: 2,
      rating: 4.8,
    },
    createdAt: "2026-08-19",
  },
  {
    id: "jo-backpack-side",
    title: "Backpack side pocket",
    category: "backpack",
    placement: "Side pocket",
    stickerSize: "3in x 3in decal",
    price: 16,
    durationDays: 21,
    status: "live",
    contexts: ["gym", "campus"],
    city: "Seattle",
    state: "WA",
    lat: 47.6062,
    lng: -122.3321,
    seller: {
      id: "jo",
      name: "Jo L.",
      avatarInitial: "J",
      memberSince: "2026",
      listingsCount: 1,
      rating: 5.0,
    },
    createdAt: "2026-08-29",
  },
];

export function getListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}

export const AD_SLOTS: AdSlot[] = [
  {
    id: "homepage-banner",
    kind: "homepage_banner",
    title: "Homepage banner",
    description: "Full-width strip above the marketplace grid. Highest visibility on the site.",
    price: 500,
    available: true,
  },
  {
    id: "category-sidebar",
    kind: "category_sidebar",
    title: "Category sidebar",
    description: "Rail alongside browse results, shown while people filter by category.",
    price: 150,
    available: true,
  },
  {
    id: "sponsored-listing",
    kind: "sponsored_listing",
    title: "Sponsored listing slot",
    description: "Sits inside the marketplace grid, styled like a listing but clearly labeled.",
    price: 75,
    available: true,
  },
];

export const JUST_SOLD: { brand: string; listingId: string; hoursAgo: number }[] = [
  { brand: "Northwind", listingId: "maya-laptop-lid", hoursAgo: 2 },
  { brand: "Fieldnote", listingId: "priya-backpack", hoursAgo: 6 },
  { brand: "Cursorly", listingId: "sam-phone-case", hoursAgo: 9 },
  { brand: "Northwind", listingId: "owen-bike", hoursAgo: 14 },
];

export const SELLER_PURCHASES: Purchase[] = [
  {
    id: "req-1",
    listing: getListing("maya-laptop-lid")!,
    brandName: "Northwind",
    price: 45,
    status: "awaiting_approval",
    purchasedAt: "2026-09-03T10:00:00Z",
  },
  {
    id: "req-2",
    listing: LISTINGS[0],
    brandName: "Fieldnote",
    price: 28,
    status: "awaiting_approval",
    purchasedAt: "2026-09-02T14:00:00Z",
  },
];

export const BRAND_PURCHASES: Purchase[] = [
  {
    id: "b-1",
    listing: getListing("maya-laptop-lid")!,
    brandName: "Northwind",
    price: 45,
    status: "awaiting_approval",
    purchasedAt: "2026-09-03T10:00:00Z",
  },
  {
    id: "b-2",
    listing: getListing("owen-bike")!,
    brandName: "Northwind",
    price: 34,
    status: "live",
    purchasedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "b-3",
    listing: getListing("sam-phone-case")!,
    brandName: "Northwind",
    price: 18,
    status: "live",
    purchasedAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "b-4",
    listing: getListing("lena-car")!,
    brandName: "Northwind",
    price: 60,
    status: "expired",
    purchasedAt: "2026-06-01T10:00:00Z",
  },
];
